Domain: "<domain.tld>"
DomainZoneID: "<DomainZoneID>"
SubDomainToUpdate: "<subdomain>" # Leave empty (or removed) to modify the domain's root
APIKey: "<Your API Key>"
DisableIPv4: false
DisableIPv6: false
ScriptOnChange: "myScript.sh" # IPversion, OldIP, NewIP. IP Version ("v4" or "v6"). It is called once per IP version changed
LogFile: "/var/log/ddns-cf/ddns-cf.log"
DebugLevel: "debug"
